FROM python:3.11

ENV BOT_TOKEN ${BOT_TOKEN}

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY .env /app/.env

EXPOSE 8000

CMD [ "python3", "./bot.py" ]
